#ifndef ENRON_PSA_CRYPTO_CONFIG_H
#define ENRON_PSA_CRYPTO_CONFIG_H

#define PSA_WANT_ALG_SHA_256 1
#define PSA_WANT_ALG_CTR 1
#define PSA_WANT_ALG_PURE_EDDSA 1
#define PSA_WANT_KEY_TYPE_AES 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR 1
#define PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY 1
#define PSA_WANT_ECC_TWISTED_EDWARDS_255 1
#define PSA_WANT_KEY_TYPE_HMAC 1
#define PSA_WANT_KEY_TYPE_DERIVE 1
#define PSA_WANT_KEY_TYPE_RAW_DATA 1

#endif
